version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - frontend

  django:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - django-code:/odn_api
    # entrypoint: ./wait-for-it.sh db:5432 --
    command:
      - sh
      - -c
      - |
        python manage.py migrate --no-input
        python manage.py collectstatic --no-input
        python manage.py createsu
        gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    networks:
      - frontend
      - backend

  db:
    image: postgis/postgis
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: local_gis_db
      POSTGRES_USER: doc2kim
      POSTGRES_PASSWORD: doc2password!
      POSTGRES_HOST: doc2db
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres-data:
  django-code:
