version: "3.9"

services:
  django:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile

    image: 030305457537.dkr.ecr.ap-northeast-2.amazonaws.com/odnapi/django

    expose:
      - "8000"
    entrypoint:
      - /docker-entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

    networks:
      - app

  nginx:
    platform: linux/amd64
    build:
      context: ./nginx
      dockerfile: ./Dockerfile

    image: 030305457537.dkr.ecr.ap-northeast-2.amazonaws.com/odnapi/nginx

    ports:
      - "80"
    entrypoint:
      - /docker-entrypoint.sh

    depends_on:
      - django
    networks:
      - app

networks:
  app:


