branch-defaults:
  master:
    environment: odn-api-dev2
    group_suffix: null
environment-defaults:
  odn-api-dev:
    branch: null
    repository: null
global:
  application_name: odn_api
  branch: null
  default_ec2_keyname: odnkey
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: odnAWS
  repository: null
  sc: git
  workspace_type: Application
