# Generated by Django 4.0.4 on 2022-05-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('buoy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('voltage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_buoy', to='buoy.buoy')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('oxy', models.FloatField()),
                ('ph', models.FloatField()),
                ('ppt', models.FloatField()),
                ('orp', models.IntegerField()),
                ('o4e', models.IntegerField()),
                ('crc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_buoy', to='buoy.buoy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_location', to='buoy.location')),
            ],
        ),
    ]
