# Generated by Django 4.0.5 on 2022-06-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('id', models.IntegerField(help_text='Buoy ID', primary_key=True, serialize=False)),
                ('voltage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('buoy_id', models.ForeignKey(db_column='buoy_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buoy_id', to='buoy.buoy')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('coordinate', models.ForeignKey(db_column='coordinate_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinate', to='buoy.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('oxy', models.FloatField()),
                ('ph', models.FloatField()),
                ('ppt', models.FloatField()),
                ('orp', models.IntegerField()),
                ('c4e', models.IntegerField()),
                ('crc', models.CharField(max_length=100)),
                ('measure_time', models.ForeignKey(db_column='measure_time_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measure_time', to='buoy.measuretime')),
            ],
        ),
    ]
