# Generated by Django 4.1.2 on 2022-10-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("mounted", "Mounted"), ("buoy", "Buoy")],
                default="buoy",
                help_text="디바이스 타입",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="owner",
            field=models.CharField(default="ODN", help_text="소유자", max_length=200),
        ),
    ]
