# Generated by Django 4.1.2 on 2022-10-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_device_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("mounted", "Mounted"), ("buoy", "Buoy")],
                default="buoy",
                help_text="디바이스 타입",
                max_length=50,
            ),
        ),
    ]
